name: CI

on:
  push:
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Check formatting
        run: nix develop --command treefmt --fail-on-change

  lighthouse:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Build the site
        run: nix develop --command just build

      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v12
        with:
          # no urls needed, since it uses local folder to scan .html files
          configPath: "./lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
